name: 打包存档管理器

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: |
          pip install -r requirements.txt
      
      # 下载 UPX
      - name: 下载 UPX
        run: |
          curl -L -o upx.zip https://github.com/upx/upx/releases/download/v5.1.1/upx-5.1.1-win64.zip
          unzip upx.zip
          echo "UPX 下载完成，版本 5.1.1"
      
      - name: 打包成 exe
        run: |
          cd src
          pyinstaller -F --noconsole --icon="../icon.ico" --name="存档管理器" --add-data="../img;img" --add-data="../fonts;fonts" --upx-dir="../upx-5.1.1-win64" main.py
      
      - name: 上传 exe 文件
        uses: actions/upload-artifact@v4
        with:
          name: SaveManager-Windows
          path: src/dist/*.exe